import type { WorktreeSnapshot } from "../../controller/workspace-snapshot";

export const worktree: WorktreeSnapshot = {
  appLabel: "App",
  apps: [
    {
      id: "chat",
      label: "Chat",
      directUrl: "http://127.0.0.1:3000",
      listening: true,
      open: true,
      ownership: "owned",
      port: 3000,
      protocol: "http",
      readiness: "ready",
      routeState: "active",
      url: "http://chat.project.repo.localhost:1355",
    },
    {
      id: "site",
      label: "Site",
      directUrl: "http://127.0.0.1:3002",
      listening: false,
      open: false,
      ownership: "none",
      port: 3002,
      protocol: "http",
      readiness: "unready",
      routeState: "inactive",
      url: null,
    },
  ],
  appGroups: [],
  branch: "main",
  configuration: {
    changeBlocked: false,
    error: null,
    path: "/tmp/project/.branchbase.json",
    preference: "project-default",
    revision: "default-revision",
    source: "project-default",
    trustCommands: [],
    trustFingerprint: "default-fingerprint",
    trusted: true,
  },
  health: "partially-running",
  id: "worktree",
  isMain: true,
  name: "project",
  path: "/tmp/project",
  primaryAppGroup: "product",
  processRunning: true,
  setupState: "idle",
};
